### ISSUE TITLE
java.lang.IllegalArgumentException: x + width must be <= bitmap.width()

### ISSUE THREAD

**Issue by athkalia** [IsseiAoki/SimpleCropView#40] opened 2015-12-28 22:59 UTC
Hello,

I am getting this exception:

```
java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
 at android.graphics.Bitmap.createBitmap(Bitmap.java:698)
 at com.isseiaoki.simplecropview.CropImageView.getCroppedBitmap(SourceFile:1012)
 at bci.onClick(SourceFile:1064)
 at android.view.View.performClick(View.java:4463)
 at android.view.View$PerformClick.run(View.java:18801)
 at android.os.Handler.handleCallback(Handler.java:808)
 at android.os.Handler.dispatchMessage(Handler.java:103)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:5299)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
 at dalvik.system.NativeStart.main(Native Method)
```

every once in a while. Any idea on what's happening there?

Cheers,
Sakis

**Comment by IsseiAoki** [comment] 2015-12-29 01:18
Hi,

Which version are you using?
This bug caused by float precision.
I fixed this bug in ver.1.0.10.
If you are using ver.1.0.10 or newer version,
I have to fix it again...

**Comment by athkalia** [comment] 2015-12-29 01:58
Unfortunately I am using 1.0.10 : >

**Comment by IsseiAoki** [comment] 2015-12-29 05:45
OK, I  will fix it : )

Can you tell me more specific?

In the previous case, the exception occured when the frame size and the original image size looks equal.
(But the frame size actually was little bigger than original image by the error of float.)

**Comment by athkalia** [comment] 2015-12-29 12:13
Sorry, I can't replicate it locally, it happened to some of my users and I just saw the stacktrace in play store. If I manage to replicate it, I'll post again.

**Comment by IsseiAoki** [comment] 2016-01-07 10:39
Hi,

I can't replicate it too, but I added code for checking frame size before cropping the image.
Please try a new version 1.0.15 : )

**Comment by andrijans** [comment] 2016-01-07 14:34
I have this issue on 1.0.13 also but its happening random. I will test 1.0.15 now

**Comment by andrijans** [comment] 2016-01-14 13:30
I got it on 1.0.15 again

**Comment by andrijans** [comment] 2016-01-14 13:36
I found the case. so i load image and i just pull one of right handles to the end of image but without moving frame on screen. As soon as i move frame on screen it works

**Comment by athkalia** [comment] 2016-01-14 13:37
Well played!

**Comment by athkalia** [comment] 2016-01-14 15:54
So you'll be releasing a 1.0.16 any time soon ? :D

**Comment by IsseiAoki** [comment] 2016-01-15 02:12
@andrijans Thank you for your PR. I merged your PR and updated.

New version has been released. Please use version 1.0.16.

**Closed by IsseiAoki** 2016-01-15 02:12 UTC

**Comment by MrVilkaman** [comment] 2016-04-03 11:58
I hae this issues again in version 1.0.16 =(

**Comment by IsseiAoki** [comment] 2016-04-12 08:43
Hi,

Sorry for late response.

Version 1.1.0 has been released.
It contains bug fix for crop algorithm.
Please try sample.

2016-04-03 20:59 GMT+09:00 Zahar <notifications@github.com>:
